class QuestionBank {
  List<String> rooms = [
    'kitchen',
    'living room',
    'bedroom',
    'bathroom',
    'dining room',
    'office',
    'garage',
    'basement',
    'attic',
    'guest room',
    'library',
    'pantry',
    'closet',
    'balcony',
    'patio',
    'study',
    'playroom',
    'media room',
    'game room',
    'laundry room',
    'sunroom',
    'greenhouse',
    'storage room',
    'utility room',
    'craft room',
    'home theater',
    'studio',
    'conservatory',
    'family room',
    'entryway',
    'reading nook',
    'home office',
    'guest bathroom'
  ];

  List<String> containers = [
    'boxes',
    'drawers',
    'cabinets',
    'shelves',
    'baskets',
    'bins',
    'crates',
    'jars',
    'cans',
    'bottles',
    'tubs',
    'buckets',
    'bags',
    'cases',
    'chests',
    'caddies',
    'cartons',
    'barrels',
    'trunks',
    'pouches',
    'suitcases',
    'backpacks',
    'briefcases',
    'envelopes',
    'folders',
    'files',
    'lockers',
    'safes',
    'vaults',
    'hampers',
    'trays',
    'bowls',
    'cups',
    'mugs',
    'pitchers',
    'vases',
    'pots',
    'pans',
    'kettles',
    'baskets',
    'totes',
    'coolers',
    'thermoses',
    'flasks',
    'canteens',
    'jugs',
    'tanks',
  ];

  List<String> items = [
    'pens',
    'pencils',
    'erasers',
    'sharpeners',
    'rulers',
    'notebooks',
    'diaries',
    'journals',
    'staplers',
    'staples',
    'paperclips',
    'pushpins',
    'tapes',
    'glues',
    'scissors',
    'markers',
    'highlighters',
    'crayons',
    'colored pencils',
    'paintbrushes',
    'palettes',
    'canvases',
    'clipboards',
    'folders',
    'files',
    'index cards',
    'post-it notes',
    'whiteboards',
    'blackboards',
    'chalks',
    'calculators',
    'protractors',
    'compasses',
    'set squares',
    'stencils',
    'papers',
    'cardstocks',
    'envelopes',
    'letter openers',
    'paperweights',
    'desk organizers',
    'calendars',
    'planners',
    'sticky notes',
    'thumbtacks',
    'inks',
    'staple removers',
    'correction fluids',
    'correction tapes'
  ];

  Map<String, dynamic> limitsAndContinuityQuestions = {
    r"     $\lim_{x \to 0} \frac{\sin x}{x}$": 1,
    r"     $\lim_{x \to \infty} \frac{1}{x}$": 0,
    r"     $\lim_{x \to 1} (x^2 - 1)$": 0,
    r"     $\lim_{x \to 3} (2x + 1)$": 7,
    r"     $\lim_{x \to -1} (x^3 + 2x^2 - x - 2)$": -4,
    r"     $\lim_{x \to 2} \frac{x^2 - 4}{x - 2}$": 4,
    r"     $\lim_{x \to 0} \frac{e^x - 1}{x}$": 1,
    r"     $\lim_{x \to \infty} \frac{2x^2 + 3x + 1}{x^2}$": 2,
    r"     $\lim_{x \to 0} \frac{\ln(1 + x)}{x}$": 1,
    r"     $\lim_{x \to 1} \frac{x^2 - 1}{x - 1}$": 2,
    r"     $\lim_{x \to 0} \frac{\tan x}{x}$": 1,
    r"     $\lim_{x \to \infty} \frac{3x^3 - x}{x^3}$": 3,
    r"     $\lim_{x \to 0} \frac{\sin(2x)}{x}$": 2,
    r"     $\lim_{x \to 0} \frac{\cos x - 1}{x^2}$": -0.5,
    r"     $\lim_{x \to 2} \frac{x^2 - 4}{x^2 - 4x + 4}$": 'inf',
    r"     $\lim_{x \to 0} \frac{\sqrt{x + 1} - 1}{x}$": 0.5,
    r"     $\lim_{x \to \infty} \frac{5x^2 + 2x + 1}{x^2}$": 5,
    r"     $\lim_{x \to 0} \frac{\ln(1 + x^2)}{x^2}$": 1,
    r"     $\lim_{x \to 1} \frac{x^3 - 1}{x - 1}$": 3,
    r"     $\lim_{x \to 0} \frac{\sin^2 x}{x^2}$": 1,
    r"     $\lim_{x \to \infty} \frac{2x^3 + x}{x^3}$": 2,
    r"     $\lim_{x \to 0} \frac{e^{2x} - 1}{x}$": 2,
    r"     $\lim_{x \to 1} \frac{x^4 - 1}{x - 1}$": 4,
    r"     $\lim_{x \to 0} \frac{\sin x}{x^3}$": 'inf',
    r"     $\lim_{x \to \infty} \frac{4x^2 + 3x + 2}{x^2}$": 4,
    r"     $\lim_{x \to 0} \frac{\ln(1 + x^3)}{x^3}$": 1,
    r"     $\lim_{x \to 2} \frac{x^3 - 8}{x - 2}$": 12,
    r"     $\lim_{x \to 0} \frac{\cos x - 1}{x}$": 0,
    r"     $\lim_{x \to \infty} \frac{6x^2 + 5x + 4}{x^2}$": 6,
    r"     $\lim_{x \to 0} \frac{e^x - 1 - x}{x^2}$": 0.5,
    r"     $\lim_{x \to 1} \frac{x^5 - 1}{x - 1}$": 5,
    r"     $\lim_{x \to 0} \frac{\sin(3x)}{x}$": 3,
    r"     $\lim_{x \to \infty} \frac{7x^3 + x}{x^3}$": 7,
    r"     $\lim_{x \to 0} \frac{\ln(1 + x^4)}{x^4}$": 1,
    r"     $\lim_{x \to 2} \frac{x^4 - 16}{x - 2}$": 32,
    r"     $\lim_{x \to 0} \frac{\cos(2x) - 1}{x^2}$": -2,
    r"     $\lim_{x \to \infty} \frac{8x^2 + 7x + 6}{x^2}$": 8,
    r"     $\lim_{x \to 0} \frac{e^{3x} - 1}{x}$": 3,
    r"     $\lim_{x \to 1} \frac{x^6 - 1}{x - 1}$": 6,
    r"     $\lim_{x \to 0} \frac{\sin(4x)}{x}$": 4,
    r"     $\lim_{x \to \infty} \frac{9x^3 + x}{x^3}$": 9,
    r"     $\lim_{x \to 0} \frac{\ln(1 + x^5)}{x^5}$": 1,
    r"     $\lim_{x \to 2} \frac{x^5 - 32}{x - 2}$": 80,
    r"     $\lim_{x \to 0} \frac{\cos(3x) - 1}{x^2}$": -4.5,
    r"     $\lim_{x \to \infty} \frac{10x^2 + 9x + 8}{x^2}$": 10,
    r"     $\lim_{x \to 0} \frac{e^{4x} - 1}{x}$": 4,
    r"     $\lim_{x \to 1} \frac{x^7 - 1}{x - 1}$": 7,
    r"     $\lim_{x \to 0} \frac{\sin(5x)}{x}$": 5,
    r"     $\lim_{x \to \infty} \frac{11x^3 + x}{x^3}$": 11,
  };
}
